apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: example
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: app-deploy
